alter table HETHONGGIAMSAT_CONFIG_STORAGES alter column TIME_RANGE_ID rename to TIME_RANGE_ID__U78614 ^
alter table HETHONGGIAMSAT_CONFIG_STORAGES drop constraint FK_HETHONGGIAMSAT_CONFIG_STORAGES_ON_TIME_RANGE ;
drop index IDX_HETHONGGIAMSAT_CONFIG_STORAGES_ON_TIME_RANGE ;
alter table HETHONGGIAMSAT_CONFIG_STORAGES alter column PLACE_ID rename to PLACE_ID__U89011 ^
alter table HETHONGGIAMSAT_CONFIG_STORAGES drop constraint FK_HETHONGGIAMSAT_CONFIG_STORAGES_ON_PLACE ;
drop index IDX_HETHONGGIAMSAT_CONFIG_STORAGES_ON_PLACE ;
alter table HETHONGGIAMSAT_CONFIG_STORAGES add column PLACE_ID varchar(36) ;
alter table HETHONGGIAMSAT_CONFIG_STORAGES add column TIME_RANGE_ID varchar(36) ;
